
GET http://localhost:3000/users

###
GET http://localhost:3000/users/1


###
POST http://localhost:3000/users
Content-Type: application/json

{
    "id":1,
    "name":"Puish",
    "age":65
}

###
PUT http://localhost:3000/users
Content-Type: application/json

{
    "id":1,
    "name":"puish",
    "age":75
}

###
DELETE http://localhost:3000/users/1

###

GET http://localhost:3000/product

###
GET http://localhost:3000/product/1


###
POST http://localhost:3000/product
Content-Type: application/json

{
    "productId":1,
    "name":"rice",
    "brand":"karnool",
    "price":650
}

###
PUT http://localhost:3000/product
Content-Type: application/json

{
    "productId":1,
    "name":"ghee",
    "brand":"cow brand",
    "price":750
}

###
DELETE http://localhost:3000/product/1